dependencies:
  - name: xke-helm-microservice-a
    version: 0.1.0
    repository: http://127.0.0.1:8879/charts
  - name: xke-helm-microservice-b
    version: 0.1.0
    repository: http://127.0.0.1:8879/charts