apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice-b.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "microservice-b.name" . }}
    helm.sh/chart: {{ include "microservice-b.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microservice-b.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "microservice-b.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MONGODB_HOST
              value: "{{- printf "%s-%s" .Release.Name "mongodb" | trunc 63 | trimSuffix "" -}}"
            - name: MONGODB_PORT
              value: "{{- .Values.mongodb.service.port -}}"
            - name: SERVICE_A_URL
              value: localhost:9081
          livenessProbe:
            httpGet:
              #path: /
              path: {{ .Values.monitoringPath }}
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              #path: /
              path: {{ .Values.monitoringPath }}
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
